parameters:
#    wanasni_trajet.proposerlistener.class: Wanasni\TrajetBundle\Listener\ProposerListener

services:
    wanasni_trajet.alert_mailer:
        class: Wanasni\TrajetBundle\Services\AlertService
        arguments: [@mailer, @doctrine.orm.entity_manager, @templating]
